/**
 * The orb — a DOM particle field (ported from the Javi design). Each state maps
 * to a particle "shape" (orbit / scatter / spiral / ring) generated by a seeded
 * RNG so layouts are deterministic. A rotating layer + per-particle "vibe"
 * animation (both CSS) give it life.
 *
 * Reactivity: a single `amplitude` (0..1) is eased every frame into the
 * `--orb-energy` CSS variable, which the stylesheet uses to scale the orb and
 * brighten the haze. While LISTENING it's fed by real mic FFT; while SPEAKING by
 * TTS word-boundary pulses (Phase 2 will switch that to real FFT of Piper audio).
 *
 * The orb subscribes to the state machine to pick its shape; it never reaches
 * into other modules.
 */
import { State } from '../state/machine.js';
import { STATE_UI } from '../ui/state-presentation.js';

// Seeded PRNG (mulberry32) — deterministic particle layouts per shape.
function rng(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function makeParticles(shape) {
  const seeds = { orbit: 11, scatter: 23, spiral: 37, ring: 53 };
  const rnd = rng(seeds[shape] || 7);
  const cx = 100;
  const cy = 90;
  const out = [];
  const { cos, sin, PI, sqrt } = Math;

  const push = (dx, dy, s) => {
    s = Math.max(1.4, s);
    out.push({
      x: +(cx + dx - s / 2).toFixed(1),
      y: +(cy + dy - s / 2).toFixed(1),
      s: +s.toFixed(1),
      b: +(s * 1.7 + 2).toFixed(1),
      dur: +(0.8 + rnd() * 1.4).toFixed(2),
      del: +-(rnd() * 1.8).toFixed(2),
    });
  };

  if (shape === 'orbit') {
    for (let i = 0; i < 24; i++) {
      const a = (i / 24) * 2 * PI + (rnd() - 0.5) * 0.3;
      const r = 72 + (rnd() - 0.5) * 6;
      push(r * cos(a), r * sin(a) * 0.8, 2.4 + rnd() * 2.4);
    }
    for (let i = 0; i < 7; i++) {
      const a = rnd() * 2 * PI;
      const r = 22 + rnd() * 52;
      push(r * cos(a), r * sin(a) * 0.8, 4.4 + rnd() * 2.6);
    }
  } else if (shape === 'scatter') {
    for (let i = 0; i < 42; i++) {
      let dx = (rnd() * 2 - 1) * 90;
      let dy = (rnd() * 2 - 1) * 76;
      const e = (dx * dx) / 8100 + (dy * dy) / 5776;
      if (e > 1) {
        const f = (1 / sqrt(e)) * 0.96;
        dx *= f;
        dy *= f;
      }
      push(dx, dy, 1.6 + rnd() * 4.2);
    }
  } else if (shape === 'spiral') {
    const n = 44;
    for (let i = 0; i < n; i++) {
      const r = 84 * sqrt(i / n);
      const a = i * 2.39996;
      push(r * cos(a), r * sin(a) * 0.85, 2.4 + 3.2 * (1 - i / n) + rnd());
    }
  } else {
    // ring
    const n = 32;
    for (let i = 0; i < n; i++) {
      const R = i % 2 ? 52 : 80;
      const a = (i / n) * 2 * PI + (rnd() - 0.5) * 0.4;
      const r = R + (rnd() - 0.5) * 7;
      push(r * cos(a), r * sin(a) * 0.82, 2.4 + rnd() * 3);
    }
  }
  return out;
}

export function createOrb(host, stateMachine) {
  host.classList.add('orb-stage');
  host.innerHTML =
    '<div class="orb-haze"></div><div class="orb-box"><div class="orb-spin"></div></div>';
  const spin = host.querySelector('.orb-spin');

  function renderShape(state) {
    const ui = STATE_UI[state];
    spin.style.animation = ui.spin ? `orb-rotate ${ui.spin} linear infinite` : 'none';
    spin.innerHTML = makeParticles(ui.shape)
      .map(
        (p) =>
          `<span class="orb-p" style="left:${p.x}px;top:${p.y}px;width:${p.s}px;height:${p.s}px;` +
          `box-shadow:0 0 ${p.b}px var(--orb-glow);animation-duration:${p.dur}s;animation-delay:${p.del}s;"></span>`
      )
      .join('');
  }

  stateMachine.subscribe(renderShape);

  // Reactivity loop
  let amp = 0;
  let ampTarget = 0;
  let pulse = 0;
  function loop() {
    if (stateMachine.current === State.IDLE) {
      ampTarget = 0.08 + Math.sin(Date.now() / 900) * 0.05;
    }
    amp += (ampTarget - amp) * 0.12;
    pulse *= 0.9;
    const energy = Math.min(1, amp + pulse);
    host.style.setProperty('--orb-energy', energy.toFixed(3));
    requestAnimationFrame(loop);
  }

  return {
    start() {
      renderShape(stateMachine.current);
      loop();
    },
    setAmplitudeTarget(v) {
      ampTarget = Math.max(0, Math.min(1, v));
    },
    pulse() {
      pulse = 0.9;
      ampTarget = 0.5;
    },
  };
}
