/**
 * The orb — a DOM particle field (ported from the Javi design). Each state maps
 * to a particle "shape" (orbit / scatter / spiral / ring) generated by a seeded
 * RNG so layouts are deterministic.
 *
 * Smooth morphing (ADR-001): the particle pool is built ONCE and never rebuilt.
 * On a state change we only re-target each particle's transform/opacity, and a
 * CSS transition glides them to the new arrangement. Each particle is split in
 * two so the morph and the idle wobble don't fight over `transform`:
 *   - outer wrapper (.orb-p) → position + size via `translate(x,y) scale(k)`,
 *     CSS-transitioned. This is what morphs between shapes.
 *   - inner <i> → the continuous "vibe" wobble + glow, with a stable per-index
 *     timing so it never restarts on a morph.
 * Rotation is a single constant speed in CSS (see .orb-spin) so changing state
 * never resets the spin.
 *
 * Reactivity: a single `amplitude` (0..1) is eased every frame into the
 * `--orb-energy` CSS variable (orb scale + haze brightness). Fed by mic FFT or
 * (mostly) speech/TTS pulses. The orb subscribes to the state machine for its
 * shape; it never reaches into other modules.
 */
import { State } from '../state/machine.js';
import { STATE_UI } from '../ui/state-presentation.js';

const POOL_SIZE = 44; // max particle count across all shapes (spiral)
const BASE = 6; // base particle diameter in px; per-particle size = scale * BASE
const CENTER = { x: 100, y: 90 }; // layout origin (matches makeParticles)

// Seeded PRNG (mulberry32) — deterministic particle layouts per shape.
function rng(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Returns particle centers + sizes for a shape: { cx, cy, s }[].
function makeParticles(shape) {
  const seeds = { orbit: 11, scatter: 23, spiral: 37, ring: 53 };
  const rnd = rng(seeds[shape] || 7);
  const cx = CENTER.x;
  const cy = CENTER.y;
  const out = [];
  const { cos, sin, PI, sqrt } = Math;

  const push = (dx, dy, s) => {
    s = Math.max(1.4, s);
    out.push({ cx: +(cx + dx).toFixed(1), cy: +(cy + dy).toFixed(1), s: +s.toFixed(1) });
  };

  if (shape === 'orbit') {
    for (let i = 0; i < 24; i++) {
      const a = (i / 24) * 2 * PI + (rnd() - 0.5) * 0.3;
      const r = 72 + (rnd() - 0.5) * 6;
      push(r * cos(a), r * sin(a) * 0.8, 2.4 + rnd() * 2.4);
    }
    for (let i = 0; i < 7; i++) {
      const a = rnd() * 2 * PI;
      const r = 22 + rnd() * 52;
      push(r * cos(a), r * sin(a) * 0.8, 4.4 + rnd() * 2.6);
    }
  } else if (shape === 'scatter') {
    for (let i = 0; i < 42; i++) {
      let dx = (rnd() * 2 - 1) * 90;
      let dy = (rnd() * 2 - 1) * 76;
      const e = (dx * dx) / 8100 + (dy * dy) / 5776;
      if (e > 1) {
        const f = (1 / sqrt(e)) * 0.96;
        dx *= f;
        dy *= f;
      }
      push(dx, dy, 1.6 + rnd() * 4.2);
    }
  } else if (shape === 'spiral') {
    const n = 44;
    for (let i = 0; i < n; i++) {
      const r = 84 * sqrt(i / n);
      const a = i * 2.39996;
      push(r * cos(a), r * sin(a) * 0.85, 2.4 + 3.2 * (1 - i / n) + rnd());
    }
  } else {
    // ring
    const n = 32;
    for (let i = 0; i < n; i++) {
      const R = i % 2 ? 52 : 80;
      const a = (i / n) * 2 * PI + (rnd() - 0.5) * 0.4;
      const r = R + (rnd() - 0.5) * 7;
      push(r * cos(a), r * sin(a) * 0.82, 2.4 + rnd() * 3);
    }
  }
  return out;
}

export function createOrb(host, stateMachine) {
  host.classList.add('orb-stage');
  host.innerHTML =
    '<div class="orb-haze"></div><div class="orb-box"><div class="orb-spin"></div></div>';
  const spin = host.querySelector('.orb-spin');

  // Build the particle pool once. Each particle keeps a stable wobble timing so
  // morphs never restart its animation.
  const timing = rng(99);
  const pool = [];
  const frag = document.createDocumentFragment();
  for (let i = 0; i < POOL_SIZE; i++) {
    const wrap = document.createElement('span');
    wrap.className = 'orb-p';
    const inner = document.createElement('i');
    inner.style.animationDuration = `${(0.8 + timing() * 1.4).toFixed(2)}s`;
    inner.style.animationDelay = `${(-(timing() * 1.8)).toFixed(2)}s`;
    wrap.appendChild(inner);
    frag.appendChild(wrap);
    pool.push(wrap);
  }
  spin.appendChild(frag);

  function renderShape(state) {
    const ps = makeParticles(STATE_UI[state].shape);
    for (let i = 0; i < POOL_SIZE; i++) {
      const el = pool[i];
      if (i < ps.length) {
        const p = ps[i];
        el.style.opacity = '1';
        el.style.transform = `translate(${p.cx}px, ${p.cy}px) scale(${(p.s / BASE).toFixed(3)})`;
      } else {
        // Unused for this shape: collapse to the center and fade out.
        el.style.opacity = '0';
        el.style.transform = `translate(${CENTER.x}px, ${CENTER.y}px) scale(0)`;
      }
    }
  }

  stateMachine.subscribe(renderShape);

  // Reactivity loop
  let amp = 0;
  let ampTarget = 0;
  let pulse = 0;
  function loop() {
    if (stateMachine.current === State.IDLE) {
      ampTarget = 0.08 + Math.sin(Date.now() / 900) * 0.05;
    }
    amp += (ampTarget - amp) * 0.12;
    pulse *= 0.9;
    const energy = Math.min(1, amp + pulse);
    host.style.setProperty('--orb-energy', energy.toFixed(3));
    requestAnimationFrame(loop);
  }

  return {
    start() {
      renderShape(stateMachine.current);
      loop();
    },
    setAmplitudeTarget(v) {
      ampTarget = Math.max(0, Math.min(1, v));
    },
    pulse() {
      pulse = 0.9;
      ampTarget = 0.5;
    },
  };
}
